-- | This file exists only for testing purposes.
-- | The actual implementation in the user's project
-- | is generated by the `oclis build` command.

module Oclis.SpecEmbed where

fileContent :: String
fileContent =
  """
    {
      "name": "placeholder",
      "description": "This is a placeholder command"
    }
  """
