// CAUTION:
// THIS FILE WAS GENERATED BY Oclis {{version}} BASED ON `oclis.ncl`.
// DO NOT EDIT MANUALLY!

use serde::Deserialize;
use std::fmt;

/// Primitive CLI argument values
#[derive(Debug, Clone, PartialEq)]
pub enum CliArgPrim {
    TextArg(String),
    IntArg(i64),
    NumberArg(f64),
    BooleanArg(bool),
    NullArg,
}

impl fmt::Display for CliArgPrim {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CliArgPrim::TextArg(s) => write!(f, "{s}"),
            CliArgPrim::IntArg(i) => write!(f, "{i}"),
            CliArgPrim::NumberArg(n) => write!(f, "{n}"),
            CliArgPrim::BooleanArg(b) => write!(f, "{b}"),
            CliArgPrim::NullArg => write!(f, "null"),
        }
    }
}

/// A full CLI invocation is a Vec of CliArguments
#[derive(Debug, Clone, PartialEq)]
pub enum CliArgument {
    CmdArg(String),
    FlagShort(char),
    FlagLong(String),
    OptionShort(char, CliArgPrim),
    OptionShortList(char, Vec<CliArgPrim>),
    OptionLong(String, CliArgPrim),
    OptionLongList(String, Vec<CliArgPrim>),
    ValArg(CliArgPrim),
    ValArgList(Vec<CliArgPrim>),
}

impl fmt::Display for CliArgument {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            CliArgument::CmdArg(cmd) => write!(f, "{cmd}"),
            CliArgument::FlagShort(flag) => write!(f, "-{flag}"),
            CliArgument::FlagLong(flag) => write!(f, "--{flag}"),
            CliArgument::OptionShort(name, val) => write!(f, "-{name}={val}"),
            CliArgument::OptionShortList(name, vals) => {
                let s: Vec<String> =
                    vals.iter().map(|v| v.to_string()).collect();
                write!(f, "-{name}={}", s.join(","))
            }
            CliArgument::OptionLong(name, val) => {
                write!(f, "--{name}={val}")
            }
            CliArgument::OptionLongList(name, vals) => {
                let s: Vec<String> =
                    vals.iter().map(|v| v.to_string()).collect();
                write!(f, "--{name}={}", s.join(","))
            }
            CliArgument::ValArg(val) => write!(f, "{val}"),
            CliArgument::ValArgList(vals) => {
                let s: Vec<String> =
                    vals.iter().map(|v| v.to_string()).collect();
                write!(f, "{}", s.join(","))
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
pub struct Argument {
    pub name: String,
    pub description: String,
    #[serde(rename = "type")]
    pub arg_type: String,
    pub optional: Option<bool>,
    pub default: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CliOption {
    pub name: Option<String>,
    pub short_name: Option<String>,
    pub description: String,
    pub argument: Option<Argument>,
    pub optional: Option<bool>,
    pub default: Option<serde_json::Value>,
}

#[derive(Debug, Clone, PartialEq, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Oclis {
    pub name: String,
    pub description: String,
    pub version: Option<String>,
    pub enforce_valid_name: Option<bool>,
    pub func_name: Option<String>,
    pub options: Option<Vec<CliOption>>,
    pub arguments: Option<Vec<Argument>>,
    pub commands: Option<Vec<Oclis>>,
}
